Einkaufsliste_RoR/config/routes.rb
EinkaufslisteRor::Application.routes.draw do
  resources :addresses

  resources :stores

  resources :articles

  resources :shoppinglists

  resources :users
  
  resources :listings

  get "users/select/:id" => "users#select", as: "select_user"
  
  
  get "shoppinglists/select/:id" => "shoppinglists#select", as: "select_shoppinglist" 
  
  
  post "listings/add" => "listings#add", as: "add"
  
  post "listings/:list_id/edit/:article_id" => "listings#edit", as: "edit"
  
  
  get "stores/new_article_store_ref/:article_id" => "stores#new_article_store_ref", as: "new_article_store_ref"
  
  post "stores/create_article_store_ref/:article_id" => "stores#create_article_store_ref", as: "create_article_store_ref"
  
  post "stores/add_article_store_ref/:article_id" => "stores#add_article_store_ref", as: "add_article_store_ref"
  
  post "stores/:id/delete_address_ref/:address_id" => "stores#delete_address_ref", as: "delete_address_ref"
  
  post "stores/:id/delete_article_ref/:article_id" => "stores#delete_article_ref", as: "delete_article_ref"
  
  post "stores/add_address/:id" => "stores#add_address", as: "add_address"
  
  post "stores/add_article/:id" => "stores#add_article", as: "add_article"
 
 
  get "addresses/new_store_address_ref/:store_id" => "addresses#new_store_address_ref", as: "new_store_address_ref"
 
  post "addresses/create_store_address_ref/:store_id" => "addresses#create_store_address_ref", as: "create_store_address_ref"
  
  post "addresses/add_store_address_ref/:store_id" => "addresses#add_store_address_ref", as: "add_store_address_ref"
 
 
  get "articles/new_store_article_ref/:store_id" => "articles#new_store_article_ref", as: "new_store_article_ref"
 
  post "articles/create_store_store_article_ref/:store_id" => "articles#create_store_article_ref", as: "create_store_article_ref"
 
  post "articles/add_store_article_ref/:store_id" => "articles#add_store_article_ref", as: "add_store_article_ref"
 
  post "articles/:id/delete_store_ref/:store_id" => "articles#delete_store_ref", as: "delete_store_ref"
  
  post "articles/add_store/:id" => "articles#add_store", as: "add_store"
  

  root :to => 'welcome#index'

end

Einkaufsliste_RoR/app/models/store.rb
class Store < ActiveRecord::Base
  # accessible attributes
  attr_accessible :name, :addresses
  
  # validation
  validates :name, :presence => true, :allow_nil => false, :allow_blank => false
  
  #validate uniqueness
  validates :name, :uniqueness => true
  
  # references
  has_and_belongs_to_many :addresses
  has_and_belongs_to_many :articles
end

Einkaufsliste_RoR/app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores, :include => :addresses }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])
    @mapped_address = Address.find_by_id(params[:address_id])
    
    # if address is not found (nil), nothing was selected by the selectbox
    if @mapped_address.nil? 
      # check if user want to assign the store with a new address
      if params[:street] != ""
        if params[:zipcode] != ""
          if params[:city] != ""
            @new_address = Address.new(:city => params[:city], :street => params[:street], :zipcode => params[:zipcode])
            @new_address.save
            @store.addresses << @new_address
          end
        end
      end
    else
      # can assign the selected address to store
      @store.addresses << @mapped_address
    end

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_path, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to stores_path, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
  
  
  def add_address
    @current_store = Store.find(params[:id])
    redirect_to new_store_address_ref_path(@current_store)
  end
  
  def add_article
    @current_store = Store.find(params[:id])
    redirect_to new_store_article_ref_path(@current_store)
  end
    
  def delete_address_ref
    @store = Store.find(params[:id])
    @address = Address.find(params[:address_id])
    
    @store.addresses.delete(@address)    
    
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
  
  def delete_article_ref
    @store = Store.find(params[:id])
    @article = Article.find(params[:article_id])
    
    @store.articles.delete(@article)
    
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
  
  def new_article_store_ref
    @store = Store.new
    @current_article = Store.find_by_id(:article_id)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end
  
  def create_article_store_ref
    @store = Store.new(params[:store])
    @current_article = Article.find_by_id(params[:article_id])
    
    @current_article.stores << @store
    
    respond_to do |format|
      if @store.save
        format.html { redirect_to articles_path, notice: 'Address was successfully created.' }
        format.json { render json: @current_article, status: :created, location: @current_article }
      else
        format.html { render action: "new_article_store_ref" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_article_store_ref
    @store = Store.new
    @current_article = Article.find_by_id(params[:article_id])
    @store_id = params[:store_id]
    
    respond_to do |format|
      if @store_id != ""
        @store = Store.find_by_id(@store_id)
        @current_article.stores.delete(@store) # prohibit duplicate references to store
        @current_article.stores << @store
      
        format.html { redirect_to articles_path, notice: 'Store was successfully added.' }
        format.json { render json: @current_article, status: :added, location: @current_article }
      else 
        format.html { render action: "new_article_store_ref" }
        format.json { render json: @current_article, status: :no_action, location: @current_article }
      end
    end
  end
end

Einkaufsliste_RoR/app/helpers/stores_helper.rb
module StoresHelper
end

Einkaufsliste_RoR/app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="myTable" >
    <tr id="head" >
    	<th> <%= f.label :name %> </th>
		</tr>	
		<tr id="content" >
			<td> <%= f.text_field :name %> </td>
		</tr>
	</table>
	<br/>
  <table class="myTable" >
  	<caption style="text-align: left;">Optional: </caption>
		<tr id="head">
			<th> <%= label_tag 'street', 'Street' %> </th>
	    	<th> <%= label_tag 'zipcode', 'ZipCode' %> </th>
	    	<th> <%= label_tag 'city', 'City' %> </th>
	    	<th style="border-left:black solid 2px;"> Or</th>
	  </tr>
		<tr id="content">
			<td> <%= text_field_tag :street, nil,:size => 8%></td>
			<td> <%= text_field_tag :zipcode, nil, :size => 4 %></td>
			<td> <%= text_field_tag :city, nil,:size => 8 %> </td>
			<td style="border-left:black solid 2px;">
				<%= select_tag :address_id, options_for_select(
						Address.all.map { |a| [ a.street + ", " + a.zipcode + " " + a.city , a.id] }
					), :prompt => "Choose an Address", 
					:onChange => 'javascript:onchange_handler()'
				%>
			</td>
		</tr>
  </table>
  <br/>
  <div class="submit">
  	<%= f.submit %>
  </div>
<% end %>

Einkaufsliste_RoR/app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= form_for(@store) do |f| %>
	<table class="myTable" >
	  <tr id="head" >
	  	<th> <%= f.label :name %> </th>
	  	<th></th>
		</tr>	
		<tr id="content" >
			<td> <%= f.text_field :name %> </td>
			<td> <%= f.submit %> </td>
		</tr>
	</table>
<% end %>
<br />

<div style="display: table-cell;"> <%= button_to 'Stores', stores_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/stores/index.html.erb
<h1>Listing stores</h1>
<hr />
<hr />

<% if @stores.count > 0 %>
	<% @stores.each do |store| %>
		<h2> <%= store.name %> </h2>
		<div style="display: table-cell;"><%= button_to 'Edit', edit_store_path(store), method: :get %></div>
		<div style="display: table-cell;"><%= button_to 'Delete', store, method: :delete, data: { confirm: 'Are you sure' }%></div>
		<h3> Adresses: </h3>
		<% if store.addresses.size > 0 %>
			<table>
				<tr id="head">
					<th> Street </th>
					<th> Zipcode </th>
					<th> City </th>
					<th> </th>	
				</tr>
				<% store.addresses.each do |address| %>
					<tr id="content">
						<td> <%= address.street %> </td>
						<td> <%= address.zipcode %> </td>
						<td> <%= address.city %> </td>
						<td> <%= button_to 'Delete assignment', delete_address_ref_path(:id => store,:address_id => address) , data: { confirm: 'Are you sure?' } %> </td>
					</tr>	
				<% end %>
			</table>
		<% else %>
			<p style="font-weight:bolder; color: red;"> <%= store.name %> has no assigned addresses</p>
		<% end %>
		<%= button_to 'Add address', add_address_path(store)%>
		
		<h3>Articles: </h3>
		<% if store.articles.size > 0 %>
			<table>
				<tr id="head">
					<th>Name</th>
				  <th>Price</th>
				  <th></th>
				</tr>
				<% store.articles.each do |article|%>
				<tr id="content">
					<td> <%= article.name %></td>
	    		<td> <%= number_to_currency article.price, :unit => "&euro;", :separator => "," %> </td>
	    		<td> <%= button_to 'Delete assignment', delete_article_ref_path(:id => store,:article_id => article) , data: { confirm: 'Are you sure?' } %> </td>
				</tr>
				<% end %>
			</table>
		<% else %>
			<p style="font-weight:bolder; color: red;"> <%= store.name %> has no assigned articles</p>
		<% end %>
		<%= button_to 'Add article', add_article_path(store)%>
		<br />		
		<hr/>
	<% end %>
<% else %>
	<h3 style="font-weight: bolder; color: red;"> No stores are created yet </h3>
<% end %>

<div style="display: table-cell;"> <%= button_to 'New Store', new_store_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Addresses', addresses_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/stores/new.html.erb
<% content_for(:head) do %>
<script language="javascript">
	function onchange_handler() {
		if ( document.getElementById('address_id').selectedIndex > 0 )
		 {
		 	document.getElementById('street').disabled = true;
		 	document.getElementById('zipcode').disabled = true;
		 	document.getElementById('city').disabled = true;
		 }
		else 
		 {
		 	document.getElementById('street').disabled = false;
		 	document.getElementById('zipcode').disabled = false;
		 	document.getElementById('city').disabled = false;
		 }
	}
</script>
<% end %>

<h1>New store</h1>
<hr/>
<hr/>

<%= render 'form' %>
<hr />

<div style="display: table-cell;"> <%= button_to 'Stores', stores_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/stores/new_article_store_ref.html.erb
<% @current_article = Article.find(params[:article_id]) %>

<% if @current_article.nil? %>

<% else %>
	<h1>Add store to article "<%= @current_article.name %>"</h1>

	<%= form_for @store, :url => create_article_store_ref_path(@current_article) do |f| %>
		<% if @store.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>
	
	      <ul>
	      <% @store.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
		<table class="myTable">
			<tr id="head">
				<th> <%= f.label :name%> </th>
		    <th></th>
		  </tr>
			<tr id="content">
				<td> <%= f.text_field :name, :size => 12%></td>
				<td>
	    		<%= submit_tag 'Create and add to article' %>
				</td>
			</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
	
	<%= form_for @store, :url => add_article_store_ref_path(@current_article) do |f| %>
		<table class="myTable">
		<tr id="head">
			<th> <%= f.label 'Store' %> </th>
			<th></th>
		</tr>
		<tr id="content">
			<td>
				<%= select_tag :store_id, options_for_select(
						Store.order("name ASC").all.map { |a| [ a.name, a.id] }
					), :prompt => "Choose a store" 
				%>
			</td>
			<td><%= submit_tag 'Add to article' %></td>
		</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
<% end %>
<div style="display: table-cell;"> <%= button_to 'All articles', articles_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>