Einkaufsliste_RoR/config/routes.rb
EinkaufslisteRor::Application.routes.draw do
  resources :addresses

  resources :stores

  resources :articles

  resources :shoppinglists

  resources :users
  
  resources :listings

  get "users/select/:id" => "users#select", as: "select_user"
  
  
  get "shoppinglists/select/:id" => "shoppinglists#select", as: "select_shoppinglist" 
  
  
  post "listings/add" => "listings#add", as: "add"
  
  post "listings/:list_id/edit/:article_id" => "listings#edit", as: "edit"
  
  
  get "stores/new_article_store_ref/:article_id" => "stores#new_article_store_ref", as: "new_article_store_ref"
  
  post "stores/create_article_store_ref/:article_id" => "stores#create_article_store_ref", as: "create_article_store_ref"
  
  post "stores/add_article_store_ref/:article_id" => "stores#add_article_store_ref", as: "add_article_store_ref"
  
  post "stores/:id/delete_address_ref/:address_id" => "stores#delete_address_ref", as: "delete_address_ref"
  
  post "stores/:id/delete_article_ref/:article_id" => "stores#delete_article_ref", as: "delete_article_ref"
  
  post "stores/add_address/:id" => "stores#add_address", as: "add_address"
  
  post "stores/add_article/:id" => "stores#add_article", as: "add_article"
 
 
  get "addresses/new_store_address_ref/:store_id" => "addresses#new_store_address_ref", as: "new_store_address_ref"
 
  post "addresses/create_store_address_ref/:store_id" => "addresses#create_store_address_ref", as: "create_store_address_ref"
  
  post "addresses/add_store_address_ref/:store_id" => "addresses#add_store_address_ref", as: "add_store_address_ref"
 
 
  get "articles/new_store_article_ref/:store_id" => "articles#new_store_article_ref", as: "new_store_article_ref"
 
  post "articles/create_store_store_article_ref/:store_id" => "articles#create_store_article_ref", as: "create_store_article_ref"
 
  post "articles/add_store_article_ref/:store_id" => "articles#add_store_article_ref", as: "add_store_article_ref"
 
  post "articles/:id/delete_store_ref/:store_id" => "articles#delete_store_ref", as: "delete_store_ref"
  
  post "articles/add_store/:id" => "articles#add_store", as: "add_store"
  

  root :to => 'welcome#index'

end

Einkaufsliste_RoR/app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def new_store_address_ref
    @address = Address.new
    @current_store = Store.find_by_id(:store_id)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end
  
  def create_store_address_ref
    @current_store = Store.find_by_id(params[:store_id])
    @address = Address.new(params[:address])
    
    @current_store.addresses << @address 
    
    respond_to do |format|
      if @address.save
        format.html { redirect_to stores_path, notice: 'Address was successfully created.' }
        format.json { render json: @current_store, status: :created, location: @current_store }
      else
        format.html { render action: "new_store_address_ref" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_store_address_ref
    @address = Address.new
    @current_store = Store.find_by_id(params[:store_id])
    @address_id = params[:address_id]
    
    
    respond_to do |format|
      if @address_id != ""
        @address = Address.find_by_id(@address_id)
        @current_store.addresses.delete(@address) # prohibit duplicate references to store
        @current_store.addresses << @address
        
        format.html { redirect_to stores_path, notice: 'Address was successfully created.' }
        format.json { render json: @current_store, status: :created, location: @current_store }
      else
        format.html { render action: "new_store_address_ref" }
        format.json { render json: @current_store, status: :no_action, location: @current_store }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

Einkaufsliste_RoR/app/helpers/addresses_helper.rb
module AddressesHelper
end

Einkaufsliste_RoR/app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<table class="myTable">
		<tr id="head">
			<th> <%= f.label :street %> </th>
	    <th> <%= f.label :zipcode %> </th>
	    <th> <%= f.label :city %> </th>
	    <th></th>
	  </tr>
		<tr id="content">
			<td> <%= f.text_field :street, :size => 8%></td>
			<td> <%= f.text_field :zipcode, :size => 4 %></td>
			<td> <%= f.text_field :city, :size => 8 %> </td>
			<td>
		    <%= f.submit %>
			</td>
		</tr>
	</table>
<% end %>

Einkaufsliste_RoR/app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>
<br />

<div style="display: table-cell;"> <%= button_to 'Show', @address, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Addresses', addresses_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<hr />
<hr />

<% if @addresses.count > 0 %>
	<table>
	  <tr id="head">
	    <th>Street</th>
	    <th>Zipcode</th>
	    <th>City</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @addresses.each do |address| %>
	  <tr id="content">
	    <td><%= address.street %></td>
	    <td><%= address.zipcode %></td>
	    <td><%= address.city %></td>
	    <td><%= button_to 'Show', address, :method => :get %></td>
	    <td><%= button_to 'Edit', edit_address_path(address), :method => :get %></td>
	    <td><%= button_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
	</table>
	<br/>
<% else %>
	<h3 style="font-weight: bolder; color: red;">There are no addresses created yet</h3>
<% end %>


<div style="display: table-cell;"> <%= button_to 'New Address', new_address_path, :method => :get%> </div>
<div style="display: table-cell;"> <%= button_to 'Stores', stores_path, :method => :get%> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, :method => :get%> </div>

Einkaufsliste_RoR/app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>
<br />
<div style="display: table-cell;"> <%= button_to 'Addresses', addresses_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/addresses/new_address_ref.html.erb
<% @current_store = Store.find(params[:store_id]) %>

<% if @current_store.nil? %>

<% else %>
	<h1>Add address to store "<%= @current_store.name %>"</h1>

	<%= form_for @address, :url => create_address_ref_path(@current_store) do |f| %>
		<% if @address.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>
	
	      <ul>
	      <% @address.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
		<table class="myTable">
			<tr id="head">
				<th> <%= f.label :street %> </th>
		    <th> <%= f.label :zipcode %> </th>
		    <th> <%= f.label :city %> </th>
		    <th></th>
		  </tr>
			<tr id="content">
				<td> <%= f.text_field :street, :size => 8%></td>
				<td> <%= f.text_field :zipcode, :size => 4 %></td>
				<td> <%= f.text_field :city, :size => 8 %> </td>
				<td>
	    		<%= submit_tag 'Create and add to store' %>
				</td>
			</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
	
	<%= form_tag add_address_ref_path(@current_store) do %>
		<table class="myTable">
		<tr id="head">
			<th> <%= label_tag 'address', 'Address' %> </th>
			<th></th>
		</tr>
		<tr id="content">
			<td>
				<%= select_tag :address_id, options_for_select(
						Address.all.map { |a| [ a.street + ", " + a.zipcode + " " + a.city , a.id] }
					), :prompt => "Choose an Address", 
					:onChange => 'javascript:onchange_handler()'
				%>
			</td>
			<td><%= submit_tag 'Add to store' %></td>
		</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
<% end %>
<div style="display: table-cell;"> <%= button_to 'Back', :back, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/addresses/new_store_address_ref.html.erb
<% @current_store = Store.find(params[:store_id]) %>

<% if @current_store.nil? %>

<% else %>
	<h1>Add address to store "<%= @current_store.name %>"</h1>

	<%= form_for @address, :url => create_store_address_ref_path(@current_store) do |f| %>
		<% if @address.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>
	
	      <ul>
	      <% @address.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
		<table class="myTable">
			<tr id="head">
				<th> <%= f.label :street %> </th>
		    <th> <%= f.label :zipcode %> </th>
		    <th> <%= f.label :city %> </th>
		    <th></th>
		  </tr>
			<tr id="content">
				<td> <%= f.text_field :street, :size => 8%></td>
				<td> <%= f.text_field :zipcode, :size => 4 %></td>
				<td> <%= f.text_field :city, :size => 8 %> </td>
				<td>
	    		<%= submit_tag 'Create and add to store' %>
				</td>
			</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
	
	<%= form_tag add_store_address_ref_path(@current_store) do %>
		<table class="myTable">
		<tr id="head">
			<th> <%= label_tag 'address', 'Address' %> </th>
			<th></th>
		</tr>
		<tr id="content">
			<td>
				<%= select_tag :address_id, options_for_select(
						Address.all.map { |a| [ a.street + ", " + a.zipcode + " " + a.city , a.id] }
					), :prompt => "Choose an Address"
				%>
			</td>
			<td><%= submit_tag 'Add to store' %></td>
		</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
<% end %>
<div style="display: table-cell;"> <%= button_to 'All Stores', stores_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>


<table>
	<tr id="head">
		<th> Street: </th>
		<th> Zipcode: </th>
		<th> City: </th>
		<th> Store(s)</th>
	</tr>
	<tr id="content">
		<td> <%= @address.street %> </td>
		<td> <%= @address.zipcode %></td>
		<td> <%= @address.city %> </td>
		<td>
			<dl style="margin: 1px 18px;">
			<% if @address.stores.any? %> 
				<% @address.stores.each do |store| %>
					<li> <%= store.name %> </li>
				<% end %>
			<% end %>
			</dl> 
	</tr>
</table>

<br />

<div style="display: table-cell;"> <%= button_to 'Edit', edit_address_path(@address), method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Addresses', addresses_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>