Einkaufsliste_RoR/config/routes.rb
EinkaufslisteRor::Application.routes.draw do
  resources :addresses

  resources :stores

  resources :articles

  resources :shoppinglists

  resources :users
  
  resources :listings

  get "users/select/:id" => "users#select", as: "select_user"
  
  
  get "shoppinglists/select/:id" => "shoppinglists#select", as: "select_shoppinglist" 
  
  
  post "listings/add" => "listings#add", as: "add"
  
  post "listings/:list_id/edit/:article_id" => "listings#edit", as: "edit"
  
  
  get "stores/new_article_store_ref/:article_id" => "stores#new_article_store_ref", as: "new_article_store_ref"
  
  post "stores/create_article_store_ref/:article_id" => "stores#create_article_store_ref", as: "create_article_store_ref"
  
  post "stores/add_article_store_ref/:article_id" => "stores#add_article_store_ref", as: "add_article_store_ref"
  
  post "stores/:id/delete_address_ref/:address_id" => "stores#delete_address_ref", as: "delete_address_ref"
  
  post "stores/:id/delete_article_ref/:article_id" => "stores#delete_article_ref", as: "delete_article_ref"
  
  post "stores/add_address/:id" => "stores#add_address", as: "add_address"
  
  post "stores/add_article/:id" => "stores#add_article", as: "add_article"
 
 
  get "addresses/new_store_address_ref/:store_id" => "addresses#new_store_address_ref", as: "new_store_address_ref"
 
  post "addresses/create_store_address_ref/:store_id" => "addresses#create_store_address_ref", as: "create_store_address_ref"
  
  post "addresses/add_store_address_ref/:store_id" => "addresses#add_store_address_ref", as: "add_store_address_ref"
 
 
  get "articles/new_store_article_ref/:store_id" => "articles#new_store_article_ref", as: "new_store_article_ref"
 
  post "articles/create_store_store_article_ref/:store_id" => "articles#create_store_article_ref", as: "create_store_article_ref"
 
  post "articles/add_store_article_ref/:store_id" => "articles#add_store_article_ref", as: "add_store_article_ref"
 
  post "articles/:id/delete_store_ref/:store_id" => "articles#delete_store_ref", as: "delete_store_ref"
  
  post "articles/add_store/:id" => "articles#add_store", as: "add_store"
  

  root :to => 'welcome#index'

end

Einkaufsliste_RoR/app/models/shoppinglist.rb
class Shoppinglist < ActiveRecord::Base
  # accessible attributes 
  attr_accessible :creationDate, :name, :user_id
  
  # validation
  validates :name, :presence => true, :allow_nil => false, :allow_blank => false
  validates :user_id, :presence => true, :allow_nil => false, :allow_blank => false
  validates :creationDate, :presence => true, :allow_nil => false, :allow_blank => false
  # validate uniqueness of List
  validates :name, :uniqueness => true
  
  # relationships
  belongs_to :user
  has_many :listings, :dependent => :destroy
  has_many :articles, :through => :listings
end

Einkaufsliste_RoR/app/controllers/shoppinglists_controller.rb
class ShoppinglistsController < ApplicationController
  # GET /shoppinglists
  # GET /shoppinglists.json
  def index
    @current_user = User.find_by_id(session[:user_id])
    if @current_user.nil?
       @shoppinglists = Shoppinglist.all
    else
       @shoppinglists = @current_user.shoppinglists   
    end

    respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @shoppinglists }
    end
  end

  # GET /shoppinglists/1
  # GET /shoppinglists/1.json
  def show
    @shoppinglist = Shoppinglist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoppinglist }
    end
  end

  # GET /shoppinglists/new
  # GET /shoppinglists/new.json
  def new
    @shoppinglist = Shoppinglist.new
    @current_user = User.find_by_id(session[:user_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoppinglist }
    end
  end

  # GET /shoppinglists/1/edit
  def edit
    @shoppinglist = Shoppinglist.find(params[:id])
  end

  # POST /shoppinglists
  # POST /shoppinglists.json
  def create
    @shoppinglist = Shoppinglist.new(params[:shoppinglist])
    @current_user = User.find_by_id(session[:user_id])
    if !@current_user.nil?
      @shoppinglist.user_id = @current_user.id
    end
    
    respond_to do |format|
      if @shoppinglist.save
        format.html { redirect_to @shoppinglist, notice: 'Shoppinglist was successfully created.' }
        format.json { render json: @shoppinglist, status: :created, location: @shoppinglist }
      else
        format.html { render action: "new" }
        format.json { render json: @shoppinglist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoppinglists/1
  # PUT /shoppinglists/1.json
  def update
    @shoppinglist = Shoppinglist.find(params[:id])
    @current_user = User.find_by_id(session[:user_id])
    if !@current_user.nil?
      @shoppinglist.user_id = @current_user.id
    end

    respond_to do |format|
      if @shoppinglist.update_attributes(params[:shoppinglist])
        format.html { redirect_to @shoppinglist, notice: 'Shoppinglist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoppinglist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoppinglists/1
  # DELETE /shoppinglists/1.json
  def destroy
    @shoppinglist = Shoppinglist.find(params[:id])
    @shoppinglist.destroy

    respond_to do |format|
      format.html { redirect_to shoppinglists_url }
      format.json { head :no_content }
    end
  end
  
  def select
    @shoppinglist = Shoppinglist.find(params[:id])
    session[:shoppinglist_id] = @shoppinglist.id
    redirect_to listings_path
  end
end

Einkaufsliste_RoR/app/helpers/shoppinglists_helper.rb
module ShoppinglistsHelper
end

Einkaufsliste_RoR/app/views/shoppinglists/_form.html.erb
<%= form_for(@shoppinglist) do |f| %>
  <% if @shoppinglist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoppinglist.errors.count, "error") %> prohibited this shoppinglist from being saved:</h2>

      <ul>
      <% @shoppinglist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="myTable" >
		<tr id="head">
			<th> <%= f.label :name %> </th>
    	<th> <%= f.label "Date of creation" %> </th>
    	<% if @current_user.nil? %>
    		<th> <%= f.label :user %> </th>
    	<% end %>
    	<th></th>
	  </tr>
		<tr id="content">
			<td> <%= f.text_field :name, :size => 10 %> </td>
			<td> <%= f.date_select :creationDate %> </td>
			<% if @current_user.nil? %>
				<td> <%= f.select( :user_id, User.all.collect{|p| [ p.username, p.id ] }, {:include_blank => "Choose a User"}) %> </td>
			<% end %>
			<td> <%= f.submit %> </td>
		</tr>
  </table>
<% end %>

Einkaufsliste_RoR/app/views/shoppinglists/edit.html.erb
<h1>Editing shoppinglist</h1>

<%= render 'form' %>

<div style="display: table-cell;"> <%= button_to 'Show', @shoppinglist, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Shoppinglists', shoppinglists_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/shoppinglists/index.html.erb
<% if @current_user.nil? %>
	<h1>Listing all shoppinglists</h1>
<% else %>
	<h1> Listing shoppinglists of <%= @current_user.username %></h1>
<% end %>

<hr />
<hr />
<br />

<% if @shoppinglists.empty? %>
  <% if @current_user.nil? %>
  	<p style="font-weight: bolder; color: red;">There are no shoppinglists created yet!!</p>
  <% else %>
  	<p style="font-weight: bolder; color: red;">The User "<%= @current_user.username%>" has no shoppinglists created yet!!</p>
  <% end %>
<% else %>
	<table>
	  <tr id="head">
	    <th>Name</th>
	    <th>Creationdate</th>
	    <% if @current_user.nil?%>
	    <th>Owner</th>
	    <% end %>
	    <th>Articles</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @shoppinglists.each do |shoppinglist| %>
	  <tr id="content">
	    <td><%= shoppinglist.name %></td>
	    <td><%= shoppinglist.creationDate %></td>
	    <% if @current_user.nil? %>
	    <td><%= 
	    		tmpuser = User.find_by_id(shoppinglist.user_id)
	    		tmpuser.username
	    	%></td>
	    <% end %>
	    <td><%= button_to 'Articles', select_shoppinglist_path(shoppinglist), method: :get%></td>
	    <td><%= button_to 'Show', shoppinglist, method: :get%></td>
	    <td><%= button_to 'Edit', edit_shoppinglist_path(shoppinglist), method: :get %></td>
	    <td><%= button_to 'Destroy', shoppinglist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
	</table>
	<br />
<% end %>

<div style="display: table-cell;"> <%= button_to 'New shoppinglist', new_shoppinglist_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'All articles', articles_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'All users', users_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/shoppinglists/new.html.erb
<h1>New shoppinglist</h1>

<%= render 'form' %>

<br />

<div style="display: table-cell;"> <%= button_to 'Shoppinglists', shoppinglists_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/shoppinglists/show.html.erb
<p id="notice"><%= notice %></p>

<table>
	<tr id="head">
		<th>Name: </th>
		<th>Creationdate: </th>
		<th>User: </th>
	</tr>
	<tr id="content">
		<td> <%= @shoppinglist.name %> </td>
		<td> <%= @shoppinglist.creationDate %> </td>
		<td> <%= @shoppinglist.user_id %> </td>
	</tr>
</table>
<br />
<div style="display: table-cell;"> <%= button_to 'Edit', edit_shoppinglist_path(@shoppinglist), method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Shoppinglists', shoppinglists_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get%> </div>