Einkaufsliste_RoR/config/routes.rb
EinkaufslisteRor::Application.routes.draw do
  resources :addresses

  resources :stores

  resources :articles

  resources :shoppinglists

  resources :users
  
  resources :listings

  get "users/select/:id" => "users#select", as: "select_user"
  
  
  get "shoppinglists/select/:id" => "shoppinglists#select", as: "select_shoppinglist" 
  
  
  post "listings/add" => "listings#add", as: "add"
  
  post "listings/:list_id/edit/:article_id" => "listings#edit", as: "edit"
  
  
  get "stores/new_article_store_ref/:article_id" => "stores#new_article_store_ref", as: "new_article_store_ref"
  
  post "stores/create_article_store_ref/:article_id" => "stores#create_article_store_ref", as: "create_article_store_ref"
  
  post "stores/add_article_store_ref/:article_id" => "stores#add_article_store_ref", as: "add_article_store_ref"
  
  post "stores/:id/delete_address_ref/:address_id" => "stores#delete_address_ref", as: "delete_address_ref"
  
  post "stores/:id/delete_article_ref/:article_id" => "stores#delete_article_ref", as: "delete_article_ref"
  
  post "stores/add_address/:id" => "stores#add_address", as: "add_address"
  
  post "stores/add_article/:id" => "stores#add_article", as: "add_article"
 
 
  get "addresses/new_store_address_ref/:store_id" => "addresses#new_store_address_ref", as: "new_store_address_ref"
 
  post "addresses/create_store_address_ref/:store_id" => "addresses#create_store_address_ref", as: "create_store_address_ref"
  
  post "addresses/add_store_address_ref/:store_id" => "addresses#add_store_address_ref", as: "add_store_address_ref"
 
 
  get "articles/new_store_article_ref/:store_id" => "articles#new_store_article_ref", as: "new_store_article_ref"
 
  post "articles/create_store_store_article_ref/:store_id" => "articles#create_store_article_ref", as: "create_store_article_ref"
 
  post "articles/add_store_article_ref/:store_id" => "articles#add_store_article_ref", as: "add_store_article_ref"
 
  post "articles/:id/delete_store_ref/:store_id" => "articles#delete_store_ref", as: "delete_store_ref"
  
  post "articles/add_store/:id" => "articles#add_store", as: "add_store"
  

  root :to => 'welcome#index'

end

Einkaufsliste_RoR/app/models/article.rb
class Article < ActiveRecord::Base
  # accessible attributes
  attr_accessible :name, :price 
  
  # validation
  validates :name, :presence => true, :allow_nil => false, :allow_blank => false
  # uniqueness of touple price and name
  validates :name, :uniqueness => {:scope => :price}
  
  # references
  has_many :listings, :dependent => :destroy
  has_many :shoppinglists, :through => :listings
  has_and_belongs_to_many :stores
    
end

Einkaufsliste_RoR/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("name ASC, price ASC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles, :include => :stores }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    if !params[:stores].nil?
      # prevent assignment of empty element to stores reference
      params[:stores].delete_if { |x| x == ""}
    end
    
    if @article.price.nil?
      # user don't know the price of the article yet
      @article.price = 0
    end
    
    respond_to do |format|
      if @article.save
        if !params[:stores].nil?
          @stores = Store.find(params[:stores])
          @stores.each { |s|
            @article.stores << s
          }
        end
        
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def new_store_article_ref
    @article = Article.new
    @current_store = Store.find_by_id(:store_id)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end
  
  def create_store_article_ref
    @current_store = Store.find_by_id(params[:store_id])
    @article = Article.new(params[:article])
    
    @current_store.articles << @article
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to stores_path, notice: 'Address was successfully created.' }
        format.json { render json: @current_store, status: :created, location: @current_store }
      else
        format.html { render action: "new_store_article_ref" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def add_store_article_ref
    @article = Article.new
    @current_store = Store.find_by_id(params[:store_id])
    @article_id = params[:article_id]
    
    respond_to do |format|
      if @article_id != ""
        @article = Article.find_by_id(@article_id)
        @current_store.articles.delete(@article) # prohibit duplicate references to store
        @current_store.articles << @article
        
        format.html { redirect_to stores_path, notice: 'Address was successfully created.' }
        format.json { render json: @current_store, status: :created, location: @current_store }
      else
        format.html { render action: "new_store_article_ref" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    
    if !params[:stores].nil?
      # prevent assignment of empty element to stores reference
      params[:stores].delete_if { |x| x == ""}
    end
    
    if @article.price.nil?
      # user don't know the price of the article yet
      @article.price = 0
    end
    
    if !params[:stores].nil?
      @stores = Store.find(params[:stores])
      @stores.each { |s|
        @article.stores.delete(s) # prohibit duplicate references to store
        @article.stores << s
      }
    end
    
    respond_to do |format|
      if @article.update_attributes(params[:article])
        if params[:list_id].empty?
          format.html { redirect_to articles_path, notice: 'Article was successfully updated.' }
        else
          format.html { redirect_to select_shoppinglist_path(params[:list_id]), notice: 'Article was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
  
  def add_store
    @current_article = Article.find(params[:id])
    redirect_to new_article_store_ref_path(@current_article)
  end
  
  def delete_store_ref
    @article = Article.find(params[:id])
    @store = Store.find(params[:store_id])
    
    @article.stores.delete(@store)
    
    respond_to do |format|
      format.html { redirect_to articles_path }
      format.json { head :no_content }
    end
  end
end

Einkaufsliste_RoR/app/helpers/articles_helper.rb
module ArticlesHelper
end

Einkaufsliste_RoR/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= hidden_field_tag 'list_id', params[:list_id] %>		
	<table class="myTable">
		<tr id="head">
			<th> <%= f.label :name %> </th>
			<th> <%= f.label :price %> </th>
			<% if Store.all.count > 0 %>
				<th> <%= f.label :stores %></th>
			<% end %>
			<th> </th>
		</tr>
		<tr id="content">
			<td> <%= f.text_field :name %> </td>
			<td> <%= f.text_field :price, :size => 6 %> </td>
			<% if Store.all.count > 0 %>
			<td> <%= select_tag :stores, options_from_collection_for_select( Store.all, :id, :name ), :include_blank => true, :multiple => true, :size => 3 %></td>
			<% end %>
			<td> <%= f.submit %> </td>		
		</tr>
	</table>
<% end %>

Einkaufsliste_RoR/app/views/articles/edit.html.erb
<h1>Editing article "<%= @article.name %>"</h1>

<% if @article.stores.any? %>
<table class="myTable">
	<tr id="head">
		<th> Associated Store</th>
		<th> </th>
	</tr>
	<% @article.stores.each do |store| %>
		<tr id="content">
			<td> <%= store.name %> </td>
			<td> <%= button_to 'Delete association', delete_store_ref_path(@article,store), method: :post , data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<% end %>
<br />

<%= render 'form' %>

<br />

<% if !params[:list_id].nil? %>
	<% @current_list = Shoppinglist.find_by_id(params[:list_id]) %>
<div style="display: table-cell;"> <%= button_to 'Articles of ' + @current_list.name, select_shoppinglist_path(@current_list), method: :get %> </div>
<% end %>
<div style="display: table-cell;"> <%= button_to 'All Articles', articles_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<hr />
<hr />

<% if @articles.empty? %>
  <h3 style="font-weight: bolder; color: red;">There are no articles created yet</h3>
<% else %>
	<% @articles.each do |article|%>
		<h2> <%= article.name %></h2>
		<div style="display: table-cell;"> <%= button_to 'Edit', edit_article_path(article), method: :get %> </div>
    <div style="display: table-cell;"> <%= button_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %> </div>
		<br />
		<div style="display: table-cell; font-weight: bolder;">Price:&nbsp;</div>
		<div style="display: table-cell;"> <%= number_to_currency article.price, :unit => "&euro; ", :separator => "," %> </div>
		
		<h3> Stores: </h3>
		<% if article.stores.size > 0 %>
			<table>
				<tr id="head">
					<th> Name </th>
					<th> </th>	
				</tr>
				<% article.stores.each do |store| %>
					<tr id="content">
						<td> <%= store.name %> </td>
						<td> <%= button_to 'Delete assignment', delete_store_ref_path(:id => article, :store_id => store) , data: { confirm: 'Are you sure?' } %> </td>
					</tr>	
				<% end %>
			</table>
		<% else %>
			<p style="font-weight:bolder; color: red;"> <%= article.name %> has no assigned addresses</p>
		<% end %>
		<%= button_to 'Add Store', add_store_path(article) %>		
		<hr />
	<% end %>
<% end %>

<div style="display: table-cell;"> <%= button_to 'New Article', new_article_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'All shoppinglists', shoppinglists_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/articles/new.html.erb
<h1>New article</h1>
<hr />
<hr />

<%= render 'form' %>

<div style="display: table-cell;"> <%= button_to 'All articles', articles_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>

Einkaufsliste_RoR/app/views/articles/new_store_article_ref.html.erb
<% @current_store = Store.find(params[:store_id]) %>

<% if @current_store.nil? %>

<% else %>
	<h1>Add article to store "<%= @current_store.name %>"</h1>

	<%= form_for @article, :url => create_store_article_ref_path(@current_store) do |f| %>
		<% if @article.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
	
	      <ul>
	      <% @article.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
		<table class="myTable">
			<tr id="head">
				<th> <%= f.label :name%> </th>
		    <th> <%= f.label :price %> </th>
		    <th></th>
		  </tr>
			<tr id="content">
				<td> <%= f.text_field :name, :size => 12%></td>
				<td> <%= f.text_field :price, :size => 4 %></td>
				<td>
	    		<%= submit_tag 'Create and add to store' %>
				</td>
			</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
	
	<%= form_tag add_store_article_ref_path(@current_store) do %>
		<table class="myTable">
		<tr id="head">
			<th> <%= label_tag 'article', 'Article' %> </th>
			<th></th>
		</tr>
		<tr id="content">
			<td>
				<%= select_tag :article_id, options_for_select(
						Article.order("name ASC, price ASC").all.map { |a| [ a.name + ", " + number_to_currency(a.price, :unit => "€", :separator => ","), a.id] }
					), :prompt => "Choose an article" 
				%>
			</td>
			<td><%= submit_tag 'Add to store' %></td>
		</tr>
		</table>
	<% end %>
	<br />
	<hr />
	<br />
<% end %>
<div style="display: table-cell;"> <%= button_to 'All Stores', stores_path, method: :get %> </div>
<div style="display: table-cell;"> <%= button_to 'Home', root_path, method: :get %> </div>